services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: onthi_frontend
    ports:
      - "5173:80"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: onthi_api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
      UPLOAD_DIR: /code/uploads
    ports:
     - "8000:8000"
    volumes:
      - uploads_data:/code/uploads
    depends_on:
      db: 
        condition: service_healthy
      redis: 
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
  
  celery_worker:
    build: 
      context: .
      dockerfile: app/Dockerfile
    container_name: onthi_celery_worker
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
      UPLOAD_DIR: /code/uploads
    volumes:
      - uploads_data:/code/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      celery -A app.core.celery_app worker --loglevel=info

  db:
    image: postgres:16
    container_name: onthi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    
  redis:
    image: redis:7
    container_name: onthi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  redis_data:
  uploads_data: